/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Screen capture interface */
export declare class Screen {
  constructor();
  /** Capture screen region */
  capture(
    x?: number | undefined | null,
    y?: number | undefined | null,
    width?: number | undefined | null,
    height?: number | undefined | null,
  ): Promise<Bitmap>;
}

/** Bitmap structure for screen capture (robotjs compatible) */
export interface Bitmap {
  width: number;
  height: number;
  image: Buffer;
  byteWidth: number;
  bitsPerPixel: number;
  bytesPerPixel: number;
}

/** Get color at specific coordinates in a bitmap */
export declare function bitmapColorAt(
  bitmap: Bitmap,
  x: number,
  y: number,
): string;

/** Capture entire screen */
export declare function captureScreen(): Promise<ScreenCaptureResult>;

/** Capture screen region */
export declare function captureScreenRegion(
  x: number,
  y: number,
  width: number,
  height: number,
): Promise<ScreenCaptureResult>;

/** Clear clipboard */
export declare function clearClipboard(): void;

/** Drag mouse */
export declare function dragMouse(x: number, y: number): void;

/**
 * Find all matches of template image in a screen region
 *
 * @param template - PNG-encoded image buffer of the template to find
 * @param x - X coordinate of search region
 * @param y - Y coordinate of search region
 * @param width - Width of search region
 * @param height - Height of search region
 * @param config - Optional matching configuration
 * @returns Array of match results (coordinates are absolute screen coordinates)
 */
export declare function findAllInRegion(
  template: Buffer,
  x: number,
  y: number,
  width: number,
  height: number,
  config?: MatchConfigJs | undefined | null,
): Promise<Array<MatchResultJs>>;

/**
 * Find all matches of template image on screen
 *
 * @param template - PNG-encoded image buffer of the template to find
 * @param config - Optional matching configuration
 * @returns Array of match results sorted by confidence
 */
export declare function findAllOnScreen(
  template: Buffer,
  config?: MatchConfigJs | undefined | null,
): Promise<Array<MatchResultJs>>;

/**
 * Find first match of template image in a screen region
 *
 * @param template - PNG-encoded image buffer of the template to find
 * @param x - X coordinate of search region
 * @param y - Y coordinate of search region
 * @param width - Width of search region
 * @param height - Height of search region
 * @param config - Optional matching configuration
 * @returns Match result or null if not found (coordinates are absolute screen coordinates)
 */
export declare function findInRegion(
  template: Buffer,
  x: number,
  y: number,
  width: number,
  height: number,
  config?: MatchConfigJs | undefined | null,
): Promise<MatchResultJs | null>;

/**
 * Find first match of template image on screen
 *
 * @param template - PNG-encoded image buffer of the template to find
 * @param config - Optional matching configuration
 * @returns Match result or null if not found
 */
export declare function findOnScreen(
  template: Buffer,
  config?: MatchConfigJs | undefined | null,
): Promise<MatchResultJs | null>;

/** Find windows by process name (case-insensitive partial match) */
export declare function findWindowsByProcess(
  processName: string,
): Array<WindowInfoResult>;

/** Find windows by title (case-insensitive partial match) */
export declare function findWindowsByTitle(
  title: string,
): Array<WindowInfoResult>;

/** Get the currently active (focused) window */
export declare function getActiveWindow(): WindowInfoResult;

/** Get a list of all visible windows */
export declare function getAllWindows(): Array<WindowInfoResult>;

/** Get text from clipboard */
export declare function getClipboard(): string;

/** Get image from clipboard (returns PNG-encoded buffer) */
export declare function getClipboardImage(): Buffer;

/** Get mouse position */
export declare function getMousePos(): MousePositionResult;

/** Get pixel color (returns hex string) */
export declare function getPixelColor(x: number, y: number): Promise<string>;

/** Get global screen instance */
export declare function getScreen(): Screen;

/** Get screen size */
export declare function getScreenSize(): ScreenSizeResult;

/** Tap a key */
export declare function keyTap(
  key: string,
  modifier?: Array<string> | undefined | null,
): void;

/** Toggle a key */
export declare function keyToggle(
  key: string,
  down: string,
  modifier?: Array<string> | undefined | null,
): void;

/** Configuration for image template matching */
export interface MatchConfigJs {
  /** Search at multiple scales (default: true) */
  searchMultipleScales?: boolean;
  /** Convert images to grayscale for matching (default: false) */
  useGrayscale?: boolean;
  /** Scale factors to search at (default: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5]) */
  scaleSteps?: Array<number>;
  /** Minimum confidence threshold 0.0-1.0 (default: 0.8) */
  confidence?: number;
  /** Maximum number of results (default: 100) */
  limit?: number;
}

/** Result from image template matching */
export interface MatchResultJs {
  /** X coordinate of match (top-left) */
  x: number;
  /** Y coordinate of match (top-left) */
  y: number;
  /** Width of matched region */
  width: number;
  /** Height of matched region */
  height: number;
  /** Confidence score 0.0-1.0 */
  confidence: number;
  /** Scale at which match was found */
  scale: number;
}

/** Mouse click */
export declare function mouseClick(
  button?: string | undefined | null,
  double?: boolean | undefined | null,
): void;

/** Mouse position */
export interface MousePositionResult {
  x: number;
  y: number;
}

/** Mouse toggle */
export declare function mouseToggle(
  down?: string | undefined | null,
  button?: string | undefined | null,
): void;

/** Move mouse */
export declare function moveMouse(x: number, y: number): void;

/** Move mouse smoothly */
export declare function moveMouseSmooth(
  x: number,
  y: number,
  speed?: number | undefined | null,
): void;

/** Pixel color information */
export interface PixelColorResult {
  r: number;
  g: number;
  b: number;
  a: number;
}

/** Screen capture result containing image data */
export interface ScreenCaptureResult {
  width: number;
  height: number;
  image: Buffer;
}

/** Screen size information */
export interface ScreenSizeResult {
  width: number;
  height: number;
}

/** Scroll mouse */
export declare function scrollMouse(x: number, y: number): void;

/** Set text to clipboard */
export declare function setClipboard(text: string): void;

/** Set image to clipboard (accepts PNG-encoded buffer) */
export declare function setClipboardImage(imageBuffer: Buffer): void;

/** Set keyboard delay */
export declare function setKeyboardDelay(ms: number): void;

/** Set mouse delay */
export declare function setMouseDelay(delay: number): void;

/** Type a string */
export declare function typeString(string: string): void;

/** Type a string with delay */
export declare function typeStringDelayed(string: string, cpm: number): void;

/** Tap a Unicode character */
export declare function unicodeTap(value: number): void;

/** Update screen metrics (no-op for now) */
export declare function updateScreenMetrics(): void;

/** Window information structure */
export interface WindowInfoResult {
  title: string;
  processId: number;
  processPath: string;
  x: number;
  y: number;
  width: number;
  height: number;
  windowId: string;
}
